# edpbox1 package
# custom

modbus:

  - name: edpbox1
    type: tcp
    host: 10.1.0.47
    port: 9502
    delay: 1
    timeout: 3
    retries: 3
    retry_on_empty: true
    message_wait_milliseconds: 750

    sensors:

      - name: "EB1 Voltage L1" # 6C
        slave: 1
        address: 108
        input_type: input
        count: 1
        data_type: uint16
        precision: 1
        scale: 0.1
        unit_of_measurement: V
        device_class: voltage
        scan_interval: 31

      - name: "EB1 Current L1" # 6D
        slave: 1
        address: 109
        input_type: input
        count: 1
        data_type: uint16
        precision: 1
        scale: 0.1
        unit_of_measurement: A
        device_class: current
        scan_interval: 32

      - name: "EB1 Active Power" # 79
        slave: 1
        address: 121
        input_type: input
        count: 1
        data_type: uint32
        precision: 0
        scale: 1
        unit_of_measurement: W
        device_class: power
        scan_interval: 33

      - name: "EB1 Power Export" # 7A
        slave: 1
        address: 122
        input_type: input
        count: 1
        data_type: uint32
        precision: 0
        scale: 1
        unit_of_measurement: W
        device_class: power
        scan_interval: 34

      - name: "EB1 Power Factor" # 7B
        slave: 1
        address: 123
        input_type: input
        count: 1
        data_type: uint16
        precision: 3
        scale: 0.001
        unit_of_measurement: pu
        device_class: power_factor
        scan_interval: 35

      - name: "EB1 Frequency" # 7F
        slave: 1
        address: 127
        input_type: input
        count: 1
        data_type: uint16
        precision: 1
        scale: 0.1
        unit_of_measurement: Hz
        scan_interval: 50

      - name: "EB1 T1 Vazio" # 26
        slave: 1
        address: 38
        input_type: input
        count: 1
        data_type: uint32
        precision: 3
        scale: 0.001
        unit_of_measurement: kWh
        device_class: energy
        scan_interval: 51

      - name: "EB1 T2 Ponta" # 27
        slave: 1
        address: 39
        input_type: input
        count: 1
        data_type: uint32
        precision: 3
        scale: 0.001
        unit_of_measurement: kWh
        device_class: energy
        scan_interval: 52

      - name: "EB1 T3 Cheias" # 28
        slave: 1
        address: 40
        input_type: input
        count: 1
        data_type: uint32
        precision: 3
        scale: 0.001
        unit_of_measurement: kWh
        device_class: energy
        scan_interval: 53

      - name: "EB1 Import" # 16
        slave: 1
        address: 22
        input_type: input
        count: 1
        data_type: uint32
        precision: 3
        scale: 0.001
        unit_of_measurement: kWh
        device_class: energy
        scan_interval: 54

      - name: "EB1 Export" # 17
        slave: 1
        address: 23
        input_type: input
        count: 1
        data_type: uint32
        precision: 3
        scale: 0.001
        unit_of_measurement: kWh
        device_class: energy
        scan_interval: 55

###

      - name: "EB1 Q1"
        slave: 1
        address: 24
        input_type: input
        count: 1
        data_type: uint32
        precision: 3
        scale: 0.001
        unit_of_measurement: kVAr
        scan_interval: 56

# templates

      - name: "EB1 0x0001" # Clock
        slave: 1
        address: 1
        input_type: input
        count: 1
        data_type: custom
        standard_size: no
        structure: ">H7BhB"
        scan_interval: 5

      - name: "EB1 0x000B" # Tariff
        slave: 1
        address: 11
        input_type: input
        count: 1
        data_type: custom
        structure: ">Bx"
        scan_interval: 31

      - name: "EB1 0x0080"
        slave: 1
        address: 128
        input_type: input
        count: 1
        data_type: custom
        standard_size: no
        structure: ">6Bxx"
        scan_interval: 32

      - name: "EB1 0x0081"
        slave: 1
        address: 129
        input_type: input
        count: 1
        data_type: custom
        standard_size: no
        structure: ">I"
        scan_interval: 33

      - name: "EB1 0x0082"
        slave: 1
        address: 130
        input_type: input
        count: 2
        data_type: custom
        standard_size: no
        structure: ">2I"
        scan_interval: 34

# strings

      - name: "EB1 Firmware Core"
        slave: 1
        address: 4
        input_type: input
        count: 1
        data_type: string
        scan_interval: 35


# edpbox mono templates custom

sensor:

  - platform: template
    sensors:

      eb1_tariff:
        friendly_name: "EB1 Tariff"
        value_template: >-
          {% set x = states('sensor.eb1_0x000b')|string %}
          {% if x == "1" %}
            {{ "Vazio" }}
          {% elif x == "2" %}
            {{ "Ponta" }}
          {% elif x == "3" %}
            {{ "Cheias" }}
          {% endif %}
        icon_template: mdi:counter

      eb1_clock:
        friendly_name: "EB1 Clock"
        value_template: >-
            {% set hh = states('sensor.eb1_0x0001').split(',')[4] | int %}
            {% set mm = states('sensor.eb1_0x0001').split(',')[5] | int %}
            {% set ss = states('sensor.eb1_0x0001').split(',')[6] | int %}
            {{ '{0:02d}'.format(hh) + ":" + '{0:02d}'.format(mm) + ":" + '{0:02d}'.format(ss) }}
        icon_template: mdi:clock

# EOF
