modbus:

  - name: edpbox9
    type: rtuovertcp
    host: 10.1.0.37
    port: 9502
    delay: 1
    timeout: 3
    retries: 3
    retry_on_empty: true
    message_wait_milliseconds: 750

    sensors:

### ### ###


      - name: "EB9 reg38 c3" # 0x0026
        slave: 1
        address: 38
        input_type: input
        count: 3
        slave_count: 2
        data_type: uint32
        precision: 1
        scale: 0.001
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
        scan_interval: 91


### ### ###

      - name: "EB9 reg22 c6" # 0x0016
        slave: 1
        address: 22
        input_type: input
        count: 6
        slave_count: 5
        data_type: uint32
        precision: 1
        scale: 0.001
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
        scan_interval: 94

### ### ###

      - name: "EB9 reg108 c7" # 0x006C
        slave: 1
        address: 108
        input_type: input
        count: 1
        slave_count: 6
        data_type: uint16
        precision: 1
        scale: 0.1
        unit_of_measurement: V
        device_class: voltage
        scan_interval: 31

### ### ###

      - name: "EB9 reg115 c4"
        slave: 1
        address: 115
        input_type: input
        count: 4
        slave_count: 3
        data_type: uint32
        precision: 0
        scale: 1
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        scan_interval: 21

      - name: "EB9 Power Export" # 0x007A
        slave: 1
        address: 122
        input_type: input
        count: 1
        data_type: uint32
        precision: 0
        scale: 1
        unit_of_measurement: W
        device_class: power
        scan_interval: 37

      - name: "EB9 Power Factor" # 0x007B
        slave: 1
        address: 123
        input_type: input
        count: 1
        data_type: uint16
        precision: 3
        scale: 0.001
        unit_of_measurement: pu
        device_class: power_factor
        scan_interval: 38

      - name: "EB9 Frequency" # 0x007F
        slave: 1
        address: 127
        input_type: input
        count: 1
        data_type: uint16
        precision: 1
        scale: 0.1
        unit_of_measurement: Hz
        scan_interval: 39


# for tariff template

      - name: "EB9 0x000B" # Tariff
        slave: 1
        address: 11
        input_type: input
        count: 1
        data_type: custom
        structure: ">Bx"
        scan_interval: 43

### for testing

      - name: "EB9 Firmware" # 0x0004
        slave: 1
        address: 4
        input_type: input
        count: 3
        data_type: string
        scan_interval: 44

### edpbox templates

sensor:

  - platform: template
    sensors:

      eb3_tariff:
        friendly_name: "EB9 Tariff"
        value_template: >-
          {% set x = states('sensor.eb9_0x000b')|string %}
          {% if x == "1" %}
            {{ "Vazio" }}
          {% elif x == "2" %}
            {{ "Ponta" }}
          {% elif x == "3" %}
            {{ "Cheias" }}
          {% endif %}
        icon_template: mdi:calendar

# EOF


# EOF
