# edpbox3 package
# standard modbus

modbus:

  - name: edpbox3
    type: tcp
    host: 10.1.0.47
    port: 9502
    delay: 1
    timeout: 3
    retries: 3
    retry_on_empty: true
    message_wait_milliseconds: 750

    sensors:

### ### ###

      - name: "EB3 T1 Vazio" # 26
        slave: 1
        address: 38
        input_type: input
        count: 1
        data_type: uint32
        precision: 1
        scale: 0.001
        unit_of_measurement: kWh
        device_class: energy
        scan_interval: 37

      - name: "EB3 T2 Ponta" # 27
        slave: 1
        address: 39
        input_type: input
        count: 1
        data_type: uint32
        precision: 1
        scale: 0.001
        unit_of_measurement: kWh
        device_class: energy
        scan_interval: 38

      - name: "EB3 T3 Cheias" # 28
        slave: 1
        address: 40
        input_type: input
        count: 1
        data_type: uint32
        precision: 1
        scale: 0.001
        unit_of_measurement: kWh
        device_class: energy
        scan_interval: 39

### ### ###

      - name: "EB3 Import" # 16
        slave: 1
        address: 22
        input_type: input
        count: 1
        data_type: uint32
        precision: 3
        scale: 0.001
        unit_of_measurement: kWh
        device_class: energy
        scan_interval: 40

      - name: "EB3 Export" # 17
        slave: 1
        address: 23
        input_type: input
        count: 1
        data_type: uint32
        precision: 3
        scale: 0.001
        unit_of_measurement: kWh
        device_class: energy
        scan_interval: 41

      - name: "EB3 Q1"
        slave: 1
        address: 24
        input_type: input
        count: 1
        data_type: uint32
        precision: 3
        scale: 0.001
        unit_of_measurement: kVAr
        scan_interval: 42

### ### ###

      - name: "EB3 Voltage L1" # 0x006C (108)
        slave: 1
        address: 108
        input_type: input
        count: 1
        data_type: uint16
        precision: 1
        scale: 0.1
        unit_of_measurement: V
        device_class: voltage
        scan_interval: 32

      - name: "EB3 Current L1" # 6D
        slave: 1
        address: 109
        input_type: input
        count: 1
        data_type: uint16
        precision: 1
        scale: 0.1
        unit_of_measurement: A
        device_class: current
        scan_interval: 33

### ### ###

      - name: "EB3 Active Power" # 79
        slave: 1
        address: 121
        input_type: input
        count: 1
        data_type: uint32
        precision: 0
        scale: 1
        unit_of_measurement: W
        device_class: power
        scan_interval: 34

      - name: "EB3 Power Export" # 7A
        slave: 1
        address: 122
        input_type: input
        count: 1
        data_type: uint32
        precision: 0
        scale: 1
        unit_of_measurement: W
        device_class: power
        scan_interval: 35

      - name: "EB3 Power Factor" # 7B
        slave: 1
        address: 123
        input_type: input
        count: 1
        data_type: uint16
        precision: 3
        scale: 0.001
        unit_of_measurement: pu
        device_class: power_factor
        scan_interval: 36

      - name: "EB3 Frequency" # 7F
        slave: 1
        address: 127
        input_type: input
        count: 1
        data_type: uint16
        precision: 1
        scale: 0.1
        unit_of_measurement: Hz
        scan_interval: 31


# for tariff template

      - name: "EB3 0x000B" # Tariff
        slave: 1
        address: 11
        input_type: input
        count: 1
        data_type: custom
        structure: ">Bx"
        scan_interval: 43

### for testing

      - name: "EB3 0x0004" # Firmwares
        slave: 1
        address: 3
        input_type: input
        count: 3
        data_type: string
        scan_interval: 44

      - name: "EB3 0x0001" # Clock
        slave: 1
        address: 0
        input_type: input
        count: 1
        data_type: string
        scan_interval: 44

### edpbox templates

sensor:

  - platform: template
    sensors:

      eb1_tariff:
        friendly_name: "EB3 Tariff"
        value_template: >-
          {% set x = states('sensor.eb3_0x000b')|string %}
          {% if x == "1" %}
            {{ "Vazio" }}
          {% elif x == "2" %}
            {{ "Ponta" }}
          {% elif x == "3" %}
            {{ "Cheias" }}
          {% endif %}
        icon_template: mdi:calendar

# EOF
