id="edpbox3"
name="EB3"


if cnt==10
then
=>Publish homeassistant/binary_sensor/%id%/status/config {"device_class":"connectivity","payload_on":"Online","payload_off":"Offline","name":"%name% Status","unique_id":"%id%_status","device":{"identifiers":"%id%_000_000","name":"%name% by Nikito","model":""}}
endif



#EOF
