id="edpbox3"
name="EB3"


if cnt==10
then
=>Publish2 homeassistant/binary_sensor/%id%/status/config {"payload_on":"Online","payload_off":"Offline","state_topic":"tele/%id%/LWT","name":"%name% Status", "unique_id":"%id%_status","device":{"identifiers":"%id%-tasmota","name":"%name%"}}
endif

if cnt==11
then
=>Publish2 homeassistant/sensor/%id%/uptime/config
{
"state_topic":"tele/%id%/STATE",
"unit_of_measurement":"h",
"icon":"mdi:chip",
"name":"%name% Uptime",
"value_template":"{{ ( value_json.UptimeSec / 3600 ) | round(1) }}",
"unique_id":"%id%_uptime","device":{"identifiers":"%id%-tasmota","name":"%name%"}}
endif

#EOF
