# edpbox3 tasmota package

switch:

  - platform: mqtt
    name: "EB3 ESP Restart"
    command_topic: "cmnd/edpbox3/restart"
    payload_on: "1"

###

sensor:

  - platform: mqtt
    name: "EB3 ESP Uptime"
    unique_id: EB3_ESP_Uptime
    state_topic: "tele/edpbox3/STATE"
    value_template: '{{ ( value_json.UptimeSec / 3600 ) | round(1) }}'
    unit_of_measurement: "h"
    icon: mdi:alarm
    availability_topic: "tele/edpbox3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "EB3 ESP Free Heap"
    unique_id: EB3_ESP_Heap
    state_topic: "tele/edpbox3/STATE"
    value_template: '{{ value_json.Heap }}'
    unit_of_measurement: "kB"
    icon: mdi:chip

  - platform: mqtt
    name: "EB3 ESP Signal"
    unique_id: EB3_ESP_Signal
    state_topic: "tele/edpbox3/STATE"
    value_template: '{{ value_json.Wifi.Signal }}'
    unit_of_measurement: "dB"
    device_class: signal_strength

  - platform: mqtt
    name: "EB3 ESP Vcc"
    unique_id: EB3_ESP_Vcc
    state_topic: "tele/edpbox3/STATE"
    value_template: '{{ value_json.Vcc|float(0.000) }}'
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement

###

  - platform: mqtt
    name: "EB3 Clock H"
    unique_id: EB3_Clock_H
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% if value_json.EB3.Clock_H is defined %}        
          {{ value_json.EB3.Clock_H }}
        {% else %}
          {{ states('sensor.eb3_clock_h') }}
        {% endif %}
    icon: mdi:clock

  - platform: mqtt
    name: "EB3 Clock M"
    unique_id: EB3_Clock_M
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% if value_json.EB3.Clock_M is defined %}        
          {{ value_json.EB3.Clock_M }}
        {% else %}
          {{ states('sensor.eb3_clock_m') }}
        {% endif %}
    icon: mdi:clock

  - platform: mqtt
    name: "EB3 Clock"
    unique_id: EB3_Clock
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% if value_json.EB3.Clock_S is defined %}
          {% set hh = states('sensor.eb3_clock_h')|int %}
          {% set mm = states('sensor.eb3_clock_m')|int %}
          {% set ss = value_json.EB3.Clock_S|int %}
          {{ '{0:02d}'.format(hh) + ":" + '{0:02d}'.format(mm) + ":" + '{0:02d}'.format(ss) }}
        {% else %}
          {{ states('sensor.eb3_clock') }}
        {% endif %}
    icon: mdi:clock

  - platform: mqtt
    name: "EB3 ESP Clock"
    unique_id: EB3_ESP_Clock
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% if value_json.Time is defined %}
          {{ value_json.Time.split('T')[1]|string }}
        {% else %}
          {{ states('sensor.eb3_esp_clock') }}
        {% endif %}
    icon: mdi:clock

###

  - platform: mqtt
    name: "EB3 Voltage L1"
    unique_id: EB3_VolL1
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.VolL1|float %}
        {% if x > 0 %}
          {{ x }}
        {% endif %}
    unit_of_measurement: "V"
    device_class: voltage

  - platform: mqtt
    name: "EB3 Voltage L1-10"
    unique_id: EB3_VolL1_10
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.VolL1 | float %}
        {% if x > 0 %}
          {{ x - 10 }}
        {% endif %}
    unit_of_measurement: "V"
    device_class: voltage

  - platform: mqtt
    name: "EB3 Voltage L2"
    unique_id: EB3_VolL2
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.VolL2|float %}
        {% if x > 0 %}
          {{ x }}
        {% endif %}
    unit_of_measurement: "V"
    device_class: voltage

  - platform: mqtt
    name: "EB3 Voltage L3"
    unique_id: EB3_VolL3
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.VolL3|float %}
        {% if x > 0 %}
          {{ x }}
        {% endif %}
    unit_of_measurement: "V"
    device_class: voltage

  - platform: mqtt
    name: "EB3 Voltage L3+10"
    unique_id: EB3_VolL3_10
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.VolL3 | float %}
        {% if x > 0 %}
          {{ x + 10 }}
        {% endif %}
    unit_of_measurement: "V"
    device_class: voltage

  - platform: mqtt
    name: "EB3 Current"
    unique_id: EB3_Current
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {{ value_json.EB3.Current|float }}
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement

  - platform: mqtt
    name: "EB3 Current L1"
    unique_id: EB3_CurL1
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {{ value_json.EB3.CurL1|float }}
    unit_of_measurement: "A"
    device_class: current

  - platform: mqtt
    name: "EB3 Current L2"
    unique_id: EB3_CurL2
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {{ value_json.EB3.CurL2|float }}
    unit_of_measurement: "A"
    device_class: current

  - platform: mqtt
    name: "EB3 Current L3"
    unique_id: EB3_CurL3
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {{ value_json.EB3.CurL3|float }}
    unit_of_measurement: "A"
    device_class: current

  - platform: mqtt
    name: "EB3 Power Factor"
    unique_id: EB3_PowFac
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.PowFac|float %}
        {% if x > 0 %}
          {{ x }}
        {% endif %}
    unit_of_measurement: "pu"
    device_class: power_factor

  - platform: mqtt
    name: "EB3 Power Factor L1"
    unique_id: EB3_PowFacL1
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.PowFacL1|float %}
        {% if x > 0 %}
          {{ x }}
        {% endif %}
    unit_of_measurement: "pu"
    device_class: power_factor

  - platform: mqtt
    name: "EB3 Power Factor L2"
    unique_id: EB3_LowFacL2
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.PowFacL2|float %}
        {% if x > 0 %}
          {{ x }}
        {% endif %}
    unit_of_measurement: "pu"
    device_class: power_factor

  - platform: mqtt
    name: "EB3 Power Factor L3"
    unique_id: EB3_PowFacL3
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.PowFacL3|float %}
        {% if x > 0 %}
          {{ x }}
        {% endif %}
    unit_of_measurement: "pu"
    device_class: power_factor

  - platform: mqtt
    name: "EB3 Active Power"
    unique_id: EB3_ActPow
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.ActPow|int %}
        {% if x %}
          {{ x }}
        {% endif %}
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement

  - platform: mqtt
    name: "EB3 Active Power L1"
    unique_id: EB3_ActLowL1
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.ActPowL1|int %}
        {% if x %}
          {{ x }}
        {% endif %}
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement

  - platform: mqtt
    name: "EB3 Active Power L2"
    unique_id: EB3_ActPowL2
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.ActPowL2|int %}
        {% if x %}
          {{ x }}
        {% endif %}
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement

  - platform: mqtt
    name: "EB3 Active Power L3"
    unique_id: EB3_ActLowL3
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.ActPowL3|int %}
        {% if x %}
          {{ x }}
        {% endif %}
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement

  - platform: mqtt
    name: "EB3 Frequency"
    unique_id: EB3_Frequency
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.Frequency|float %}
        {% if x > 0 %}
          {{ x }}
        {% endif %}
    unit_of_measurement: "Hz"
    icon: mdi:pulse

###
###

  - platform: mqtt
    name: "EB3 T1 Vazio"
    unique_id: EB3_TotEneT1
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = float(value_json.EB3.TotEneT1,-1) %}
        {% if x > 0 %}
          {{ x }}
        {% else %}
          {{ states('sensor.eb3_t1_vazio') }}
        {% endif %}
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing

  - platform: mqtt
    name: "EB3 T2 Ponta"
    unique_id: EB3_TotEneT2
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = float(value_json.EB3.TotEneT2,-1) %}
        {% if x > 0 %}
          {{ x }}
        {% else %}
          {{ states('sensor.eb3_t2_ponta') }}
        {% endif %}
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing

  - platform: mqtt
    name: "EB3 T3 Cheias"
    unique_id: EB3_TotEneT3
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = float(value_json.EB3.TotEneT3,-1) %}
        {% if x > 0 %}
          {{ x }}
        {% else %}
          {{ states('sensor.eb3_t3_cheias') }}
        {% endif %}
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing

###
###

  - platform: mqtt
    name: "EB3 Import"
    unique_id: EB3_TotEneImp
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = float(value_json.EB3.TotEneImp,-1) %}
        {% if x > 0 %}
          {{ x }}
        {% else %}
          {{ states('sensor.eb3_import') }}
        {% endif %}
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing

  - platform: mqtt
    name: "EB3 Export"
    unique_id: EB3_TotEneExp
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = float(value_json.EB3.TotEneExp,-1) %}
        {% if x > 0 %}
          {{ x }}
        {% else %}
          {{ states('sensor.eb3_export') }}
        {% endif %}
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing

###
###

  - platform: mqtt
    name: "EB3 Tariff"
    unique_id: EB3_Tariff
    state_topic: "tele/edpbox3/SENSOR"
    value_template: >-
        {% set x = value_json.EB3.Tariff|int %}
        {% if x == 1 %}
          {{ "Vazio" }}
        {% elif x == 2 %}
          {{ "Ponta" }}
        {% elif x == 3 %}
          {{ "Cheias" }}
        {% endif %}
    icon: mdi:counter

###
##
#
