#/config/pkg/modpool.yaml

sensor:

  - platform: command_line
    name: "modpoll data"
    command: "/config/apps/modpoll.sh"
    scan_interval: 20
    command_timeout: 10
    
template:

  - sensor:

    - name: "modpool test"
      state: >-
        {% set x = states('sensor.modpoll_data').split(',')[0] | float(0) %}
        {% if x > 0 %}
          {{ (x/1000)|round(1) }}
        {% endif %}

#eof
